// Created by iWeb 3.0.4 local-build-20260102

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWEmptyStroke(),stroke_0:new IWPhotoFrame([IWCreateImage('NFL___Honneurs_files/highlighter_ul.png'),IWCreateImage('NFL___Honneurs_files/highlighter_top.png'),IWCreateImage('NFL___Honneurs_files/highlighter_ur.png'),IWCreateImage('NFL___Honneurs_files/highlighter_right.png'),IWCreateImage('NFL___Honneurs_files/highlighter_lr.png'),IWCreateImage('NFL___Honneurs_files/highlighter_bottom.png'),IWCreateImage('NFL___Honneurs_files/highlighter_ll.png'),IWCreateImage('NFL___Honneurs_files/highlighter_left.png')],null,1,0.900000,17.000000,24.000000,17.000000,24.000000,33.000000,38.000000,33.000000,38.000000,40.000000,40.000000,40.000000,40.000000,null,null,null,0.500000),stroke_2:new IWStrokeParts([{rect:new IWRect(-2,2,4,20),url:'NFL___Honneurs_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'NFL___Honneurs_files/stroke_1.png'},{rect:new IWRect(2,-2,68,4),url:'NFL___Honneurs_files/stroke_2.png'},{rect:new IWRect(70,-2,4,4),url:'NFL___Honneurs_files/stroke_3.png'},{rect:new IWRect(70,2,4,20),url:'NFL___Honneurs_files/stroke_4.png'},{rect:new IWRect(70,22,4,4),url:'NFL___Honneurs_files/stroke_5.png'},{rect:new IWRect(2,22,68,4),url:'NFL___Honneurs_files/stroke_6.png'},{rect:new IWRect(-2,22,4,4),url:'NFL___Honneurs_files/stroke_7.png'}],new IWSize(72,24))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('NFL___Honneurs_files/NFL___HonneursMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
